### ISSUE TITLE
Create performance benchmarks suite.

### ISSUE THREAD

**Issue by timstaley** [transientskp/tkp#344]
There is potential to integrate this into Jenkins, but I'm interested in trying out [ASV](https://github.com/spacetelescope/asv/) as I suspect a dedidcated GUI might be much nicer.

**Comment by timstaley** [comment]
This should be in place before we start making any under-the-hood changes, so 2.1 is a good marker.

**Comment by gijzelaerr** [comment]
for now I've setup a regular nightly clean run with fixed dataset https://github.com/transientskp/tkp/issues/333

**Comment by gijzelaerr** [comment]
closing this issue. I think our jenkins build is for now good enough.
