### ISSUE TITLE
Make insert_temprunningcatalog MonetDB-Oct2014 compliant

### ISSUE THREAD

**Issue by bartscheers** [transientskp/tkp#347]
SQRT in CASE is executed too early. It should be taken outside the case statements of the _insert_temprunningcatalog queries.

**Comment by bartscheers** [comment]
PR out at https://github.com/bartscheers/tkp/pull/4

**Comment by gijzelaerr** [comment]
tim said he will have a look so I assign this one to tim!

**Comment by timstaley** [comment]
Right, I've rebased this and pulled it into this repo as branch https://github.com/transientskp/tkp/tree/monetdb-oct2014-sp4 . 
It fixes several failing use-cases, however we still need to deal with infinite error-bars in some bad source fits. This needs some discussion, so I'm bumping Monet fixes to 2.2.

**Comment by bartscheers** [comment]
This is one of the reasons why Jenkins was switched of, see issue 
https://github.com/transientskp/tkp/issues/474
