### ISSUE TITLE
add support for the AARTFAAC telescope

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/tkp#356]
We need support for the AARTFAAC telescope. This is quite easy, we just need to write a new accessor that inherrits from the CASA accessor.

**Comment by gijzelaerr** [comment]
This PR implements the new accessor 

https://github.com/transientskp/tkp/pull/357

**Comment by AntoniaR** [comment]
As mentioned in the discussion on Hipchat, I think this should be for TraP release 3.0 as it is a new capability still needing work.

**Comment by gijzelaerr** [comment]
New PR https://github.com/transientskp/tkp/pull/452

**Comment by gijzelaerr** [comment]
PR has been merged.
