### ISSUE TITLE
centralize configuration

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/tkp#365]
Currently the tkp.db.database.Database reads environment variables to configure settings. I think all configuration should be done in tkp.config and in tkp.config only, while only database stuff should be happening in tkp.db.

if we don't change this, this becomes a problem with for example SQLAlchemy where now we have to configure a tkp.db.database first to get the proper configuration.

It would be nice to make the configuration a singleton, similar to tkp.db.database.Database, so you can call tkp.config anywhere in your code without worrying about duplication or initialization.

**john**: I agree with the principle. But I can't see where tkp.db.database.Database is reading environment variables -- the only place database-relevant environment variables are touched is around line 66 of tkp.config. Am I misunderstanding your point?

moved from github:
https://support.astron.nl/lofar_issuetracker/issues/4944

**Comment by AntoniaR** [comment]
This issue will likely be resolved in the new redesign of the source association and other SQL commands in TraP R7. Closing this issue.
