### ISSUE TITLE
Disabled PySE unit test

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/tkp#375]
As of 9325a5f8, TestPyse.test_handle_args() says:
TODO: disabled since clashes with nosetest arguments.

@jdswinbank: I assume the problem here is that pyse.py's handle_args() function only handles arguments provided on the command line: it's not possible to provide a "dummy" set of arguments for testing. ...except that as of 633bd0d it is, so hopefully there's no reason why we can't enable a test here.

moved from LOFAR issue tracker
https://support.astron.nl/lofar_issuetracker/issues/4840

**Comment by AntoniaR** [comment]
Unclear if this is still an issue so would be good to test with the latest version.

**Comment by HannoSpreeuw** [comment]
This is no longer occurring and probably fixed since PR #596 , more specifically following [this suggestion](https://github.com/transientskp/tkp/pull/596#issuecomment-1340623338).
