### ISSUE TITLE
Quality Control: is the full FoV imaged?

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/tkp#378]
Is the full field of view imaged?
This has been raised as an interesting test, as if the full field of view (FOV) has not been imaged we may want to image the full dataset. The imaged FOV information can be estimated using the number of pixels and the size of the pixels. (nx and ny are the number of pixels in the x and y directions and are in the image header). The full FOV can be obtained from a look-up table here: http://www.astron.nl/radio-observatory/astronomers/lofar-imaging-capabilities-sensitivity/lofar-imaging-capabilities/lofa (Table 1) or more accurately calculated using the two equations at the top of that webpage.  However this requires the array configuration - these are also inputs to the theoretical noise calculation. So keep this information as user entries for now (in same way as for the theoretical noise calculation).
If nx_ny_(cellsize/3600)*(cellsize/3600) < FOV in square degrees then image is flagged with something like "not full FOV"

For this test the image is not rejected, just flagged. So here give "Full field of view not imaged. Imaged FoV=XXdegrees, Observed FoV=XXdegrees" in the quality rejection column.

However, there are some imaging complexities which need to be taken into account here (namely the AWImager circular images). See full discussion under issue #3802

@jbroderick1: One thing to watch out for on the webpage linked above: the first equation is wrong. For the HBA, the constant should be 1.02 (uniformly illuminated circular aperture) instead of 1.3. For the LBA, the value is 1.1 according to George. Apparently the original constant was found to be too large for the case of a LOFAR station, and hence the values in the table had to be updated.

moved from LOFAR issue tracker
https://support.astron.nl/lofar_issuetracker/issues/3969

**Comment by AntoniaR** [comment]
Current quality control work has shown this test is redundant and current TraP usage often does not require the full FoV
