### ISSUE TITLE
Quality Control: Calculate an estimate of the confusion noise

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/tkp#380]
Many of the images currently being input to the TraP are confusion limited so it is not possible to reach the theoretical noise. An estimate of the confusion noise can be obtained using the following equations:

$beam = 206265_((300/$freq)/(1000_$maxbl));
$confujy = 29.0_pow($beam,1.54)_pow(($freq/74.0),-0.7);

Where $freq is the observing frequency, and $maxbl the maximum baseline.

Can this value be calculated and stored in the Image table of the database?

For more info and a discussion of the caveats: http://www.lofar.org/operations/doku.php?id=tkp:rsm_noise

original issue:
https://support.astron.nl/lofar_issuetracker/issues/4412

**Comment by AntoniaR** [comment]
Current quality control work has shown this test is redundant
