### ISSUE TITLE
Quality Control: Distance from source extraction edge

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/tkp#381]
Can we record the separation of the source and the edge of source extraction region in the extracted source table of the database? This is then relevant to issues #4246 and #4081.

Then flag (but not reject) the source in Banana if separation<X, where X an input to Banana in the future (hard coded to e.g. 10 pixels for now - unless it is really easy to do!), then we can immediately see which sources are close to the source extraction edge. This would be very useful when we have overlapping beams at the same time step and when there are bright sources off the edge of the field of view which can cause spurious sources near the image edges.

I have provisionally assigned Gijs as it is a quality control test, but probably more relevant to Tim's work...

original issue:
https://support.astron.nl/lofar_issuetracker/issues/4411

**Comment by AntoniaR** [comment]
As discussed in the pipeline meeting, this problem may be better solved by PySE having a larger analysis radius (where the RMS noise is modelled) and a smaller detection radius. This is because the spurious sources are typically due to poor modelling of the RMS noise in that region.

So I propose to make this change in PySE and then see if we still require this quality control check.

Perhaps @timstaley or @dariocarbone6 also have opinions regarding this?

**Comment by dariocarbone6** [comment]
I think what Antonia proposed and was already discussed during the meeting is a reasonable solution.
Having a larger area where to estimate the noise background and a smaller region where we extract sources.

**Comment by gijzelaerr** [comment]
ok i'll try to work on the source finder and try to model the noise over the complete image and only limit the source detection to the detection radius.

**Comment by gijzelaerr** [comment]
active development is in this branch https://github.com/transientskp/tkp/tree/aartfaac-stream which depends on this PR https://github.com/transientskp/tkp/pull/515

**Comment by AntoniaR** [comment]
This is a useful feature and solves a lot of false positives, I propose that we address this in Release 6.0

**Comment by AntoniaR** [comment]
This would be better solved by mapping the RMS grid for the full image in PySE rather than a fix later. Putting a new issue on the PySE repository.
