### ISSUE TITLE
Quality Control: Significant number of particular station type flagged

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/tkp#383]
Method:
1. Select all baselines between the imaged minimum and maximum baseline length (max_bl and min_bl given in the LOFAR_OBSERVATION table of the CASA image). The antenna id numbers are obtained from the LOFAR_ANTENNA table (i.e. find all pairs of antennas with a separation in the baseline range). For all the available baselines, identify the unique stations used and sort into core, remote and international.
2. Use the NVIS_USED and NVIS_TOTAL tables in the LOFAR_OBSERVATION table. Sum the maximum possible data available and sum the amount of data used for each type of station.
3. Calculate the percentage of flagged data ((1 - used/total)*100%) and flag the station as 'bad' if this exceeds the user defined maximum percentage allowed (same value as used in #3788).
4. Sum the number of 'bad' stations of a particular type and the total number of stations of a particular type. Use these to calculate the percentage of 'bad' baselines. Print the number of good and bad stations into the pipeline.log for each type of station. $type = (core remote international)
5. Reject image if the percentage of 'bad' stations in a particular category exceeds a user defined value (bad_station_percentage given in the quality_control.parset). Quality rejection reason: “Large amount of Measurement Set flagged. $value % of $type stations flagged.”

original issue:
https://support.astron.nl/lofar_issuetracker/issues/3884

**Comment by AntoniaR** [comment]
Current quality control work has shown this test is redundant
