### ISSUE TITLE
Quality Control: Significant number of baselines flagged

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/tkp#384]
Method:
1. Select all baselines between the imaged minimum and maximum baseline length (max_bl and min_bl given in the LOFAR_OBSERVATION table of the CASA image). The antenna id numbers are obtained from the LOFAR_ANTENNA table (i.e. find all pairs of antennas with a separation in the baseline range).
2. Use the NVIS_USED and NVIS_TOTAL tables in the LOFAR_OBSERVATION table. Obtain the maximum possible data available and the amount of data used for each baseline.
3. Calculate the percentage of flagged data ((1 - used/total)*100%) and flag the baseline as 'bad' if this exceeds the user defined maximum percentage allowed (same value as used in #3788).
4. Sum the number of 'bad' baselines and the total number of baselines. Use these to calculate the percentage of 'bad' baselines. Print the number of good and bad baselines into the pipeline.log
5. Reject image if the percentage of 'bad' baselines exceeds a user defined value (bad_baseline_percentage given in the quality_control.parset). Quality rejection reason: “Large amount of Measurement Set flagged. $value % of baselines flagged.”

original issue
https://support.astron.nl/lofar_issuetracker/issues/3883

**Comment by AntoniaR** [comment]
Current quality control work has shown this test is redundant
