### ISSUE TITLE
Quality Control: Percentage of flagged data

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/tkp#386]
In version 1, we will concentrate on the total percentage of flagged data in the measurement set. This test can be fairly easily implemented using the TAQL query:

`taql 'CALC sum([select ntrue(FLAG) from '+ $msname + '])'`

This gives the total number of flags. Changing 'ntrue' to 'nfalse' gives the total amount of unflagged data. Then simply set percent_flagged=(ntrue/nfalse)*100. The threshold for good/bad image needs to be a user entry for now, i.e. image fail if percent_flagged > X% (where X is a user entry float, default 10.0%) This method does not require the NDPPP parset file.
Input: measurement set used in imaging, parset file with the user defined threshold (it might be useful to have 1 parset file for all the pre-imaging quality control checks)
Output: Pass/Fail (When an image fails output the percentage of data flagged and the threshold used)

more discussion in the original issue
https://support.astron.nl/lofar_issuetracker/issues/3788

**Comment by AntoniaR** [comment]
Current quality control work has shown this test is redundant
