### ISSUE TITLE
TraP and AARTFAAC Noise

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/tkp#388]
(sorry, not sure what to call this issue to make it appropriately descriptive...)

For quality control of AARTFAAC images that are run through TraP and checking the RMS levels, one option would be for TraP to rewrite the theoretical noise for an arbitrary given antenna. This can be done if and when AARTFAAC images list the antennas used in their creation, though is currently missing from the AARTFAAC images.

moved from here
https://support.astron.nl/lofar_issuetracker/issues/5770

**Comment by AntoniaR** [comment]
This is likely no longer required with new processing strategies.
