### ISSUE TITLE
State the number of blind extractions from an image separately

### ISSUE THREAD

**Issue by ajstewart** [transientskp/tkp#394]
Personally I feel it would be useful to somewhere differentiate between the number of blind sources extracted from an image and the number of 'forced fits'. This would be to answer simple questions such as how many sources on average are extracted from images. It may also help with manual attempts at quality control, if suddenly the number of sources extracted drops then this is an easy sign to spot.

This also leads to the histogram on the front page of a run. For every run I do it steadily just increases to approximately double the number sources actually found in an image and levels off. I would find it more useful to know how many sources are *actually* found in each individual image rather than this cumulative representation. Though this preference may not be shared.

![numberofsources](https://cloud.githubusercontent.com/assets/3306161/6178579/35e7560e-b308-11e4-948c-54a88a46ee3e.png)

I've put this in the tkp section as I'm not sure how things are stored, i.e. if this value is easily accessible. Please move if it is purely a banana issue.

**Comment by timstaley** [comment]
Good idea Adam! We can probably do this quite easily.

**Comment by timstaley** [comment]
Although it's really a Banana issue- I'll migrate it over there.
