### ISSUE TITLE
Add trap-manage.py subcommand to delete a dataset

### ISSUE THREAD

**Issue by timstaley** [transientskp/tkp#395]
(CF https://redmine.astron.nl/lofar_issuetracker/issues/4695)
Sometimes a dataset is created in error or with poor initial parameters, it's nice for a user to be able to delete one dataset without clearing the whole database, to keep the Banana listings a bit cleaner etc.

**Comment by gijzelaerr** [comment]
we can also do this from banana. But since it is currently impossible to know who made which database this would imply everybody can delete each others datasets.

**Comment by timstaley** [comment]
Right, exactly - easy to do it with the command line tool, which already has a password/config file. (Perhaps also less prone to user error)
