### ISSUE TITLE
Split (and rename) PySE to a stand-alone package

### ISSUE THREAD

**Issue by timstaley** [transientskp/tkp#403]
CF https://redmine.astron.nl/lofar_issuetracker/issues/5687

I think this would be a good idea - separation of concerns and all that - and I'm of the opinion that managing Python package dependencies isn't that big of a deal if you're careful about your versioning and 'install_requires' entries in setup.py. But it's quite a lot of work for little immediate gain; I'm certainly open to debate.

**Comment by timstaley** [comment]
NB the name 'pyse' is already taken https://pypi.python.org/pypi/pyse

**Comment by AntoniaR** [comment]
This has been implemented by @HannoSpreeuw
