### ISSUE TITLE
Add Offline Historical Catalog Support

### ISSUE THREAD

**Issue by ajstewart** [transientskp/tkp#405]
One for the future but I couldn't see this one in the current list of issues/enhancements. Rob mentioned this the other day and I agree that it would be quite a neat feature to keep in mind. 

Basically to have the ability for the TraP to cross match with previous radio catalogues such as FIRST, VLSS, WENSS or NVSS (whichever are deemed most useful), but importantly being able to do so offline (Rob was specific with the offline bit). To say if there was a source detected historically there or not is a good initial bit of information to know.

It would probably need a bit of discussion of what exactly would be wanted from this feature. I don't think it would need to always be done, I see it as a request feature. I.e not running such a cross match on everything as I would assume that would slow things down significantly. You could envision being able to bolt on additional catalogs if ever required, but to never go crazy with it as that's what vizier is for.

For now, the simbad button is pretty useful!

**Comment by gijzelaerr** [comment]
so I think we shouldn't do this in TraP. TraP should do one thing, and that is find transients in radio image streams. In my opionin we should  let astronomers build their own specific tools in IPython notebooks. Thing is, it just doesn't scale to have us software engineers build in all these details. I think it is better to really build tools, so astronomers can build their own workflow and keep on building those in the future.

What about we create some easy tools to extract all running catalogs from TraP (thats like 5 lines of code now), create some tools to load in these other datasets and then create IPython notebook examples so astronomers can do this themself? I think that is a much more sustainable solution.

**Comment by timstaley** [comment]
See also: http://www.ir.isas.jaxa.jp/~cyamauch/2masskit (though it's optical only)

**Comment by AntoniaR** [comment]
From experience, this is now typically being handled in Jupyter notebooks accessing the VO servers directly. Example codes are going to be uploaded to the repository here https://github.com/transientskp/TraP_tools
I am going to close this issue.
