### ISSUE TITLE
Review implementation of  'Detection' objects

### ISSUE THREAD

**Issue by timstaley** [transientskp/tkp#410]
cf https://redmine.astron.nl/lofar_issuetracker/issues/4877

In short, do we really need such an awkward class to represent our sourcefinder results? What do we gain by using this over something like a namedtuple (cf the mock-testing class db_subs.ExtractedSourceTuple). And if we do gain from it, we need to ensure they're in sync.

---

@jdswinbank:

The sourcefinder's Detection class is very heavyweight: instantiating it requires setting up an image with a valid WCS etc. This is not convenient for use in unit testing other functionality, such as the database interface. Therefore, we have db_subs.ExtractedSourceTuple, which provides a named tuple supplying (to first order, at least) the same interface as Detection.

However, when changes are made to Detection, it's easy to forget that ExtractedSourceTuple should also be tweaked to match the Detection interface, and therefore it's possible for the results provided by the sourcefinder not to actually be usable by the rest of the pipeline without this being flagged up by the test suite.

A workaround would be to add another set of tests that demonstrate that ExtractedSourceTuple really does match the Detection interface.

(Or, I guess, to have both Detection and ExtactedSourceTuple inherit from the same abstract class, but I suspect that might be a more awkward solution.

**Comment by AntoniaR** [comment]
@HannoSpreeuw if I understood correctly, this is now implemented differently in PySE and hence we can close this issue?

**Comment by HannoSpreeuw** [comment]
> I would not describe the `extract.Detection` class as `awkward`. It does induce slowness, but it is properly designed, so I would like to keep it, at least for deblending purposes.

Therefore I propose closing this issue as "will not fix" .

**Comment by AntoniaR** [comment]
We close this issue as we do not think this is necessary.
