### ISSUE TITLE
[AARTFAAC] calibration pipeline generated images have center freq. and bandwidth as 0

### ISSUE THREAD

**Issue by hsuyeep** [transientskp/tkp#414]
Location of generated images: peeyush@struis:~/pipeline/testaartfaac/2013_pipeline_images

Generated using aartfaac-imaging-pipeline: commit 9ccd801a56212f7488a2aa42757903ffe1c8ef7b
Author: Error323 <folkerthuizinga@gmail.com>
Date:   Thu Feb 19 16:51:03 2015 +0100

MS location: prasad@ads001:/data/24h$ ls SB003_LBA_OUTER_8b2sbr03.MS/, via the emulator.

**Comment by hsuyeep** [comment]
I saw that the .MS does seem to have the center freq. value in the 'COORDS' keyword ('spectral1' field). Looks like TraP picks up the value from the other fields like restfrequency, which are indeed set to 0. 

From the MS header:
Table keywords: {'logtable': 'Table: /home/peeyush/pipeline/testaartfaac/2013_images/F5.72174e+07_S0-0_T20-11-2013_09-58-07.image/logtable', 'coords': {'spectral1': {'waveUnit': 'mm', 'wcs': {'pc': 1.0, 'crpix': 0.0, 'crval': 57217408.0, 'ctype': 'FREQ\x00\x00\x00\x00\x00', 'cdelt': 0.0}, 'name': 'Frequency', 'restfreqs': array([ 0.]), 'velUnit': 'km/s', 'system': 'LSRK', 'version': 2, 'velType': 0, 'restfreq': 0.0, 'formatUnit': '', 'nativeType': 0, 'unit': 'Hz', 'conversion': {'position': {'m1': {'value': 0.0, 'unit': 'rad'}, 'm2': {'unit': 'm', 'value': 0.0}, 'type': 'position', 'm0': {'value': 0.0, 'unit': 'rad'}, 'refer': 'ITRF'}

The crval of 57217408.0 is the correct value of frequency here. I guess the bandwidth should come from the cdelt value, which is also set to 0. These should probably be fixed in the image generation routines.

**Comment by gijzelaerr** [comment]
@Error323 @hsuyeep has this been fixed?

**Comment by Error323** [comment]
Yesterday the TraP was able to process AARTFAAC images.
