### ISSUE TITLE
Add more AARTFAAC quality control checks

### ISSUE THREAD

**Issue by hsuyeep** [transientskp/tkp#420]
WARNING tkp.steps.quality: Unrecognised telescope AARTFAAC All Sky Monitor for file /home/peeyush/pipeline/testaartfaac/2013_images/F5.72174e+07_S0-0_T20-11-2013_09-36-05.image, no quality checks.

I suppose this would be a small change, considering the quality control parameters are supplied in the job configuration. I see the 'quality_lofar' keyword being (ab)used currently for this... Might be better to specify this via a 'quality_aartfaac'  keyword.

**Comment by gijzelaerr** [comment]
Question is, do we want the same quality checks for AARTFAAC?

Also, are some of the LOFAR quality checks general quality checks we could perform on all telescopes?

**Comment by AntoniaR** [comment]
No we don't want all the LOFAR QC tests for AARTFAAC, but we need to design AARTFAAC specific tests. I think we should design them offline and then implement in TraP when we're happy they solve the issues (i.e. what we did for LOFAR...).

Yes, the RMS check is one that can be adapted to all telescopes. However, without the comparison to theoretical noise as this may not be known. I have already done this in an offline script (which produces the images_to_process.py file) and am planning to figure out the best way to implement in TraP in October.

**Comment by gijzelaerr** [comment]
I'm closing this issue, it is too vague, and Antonias suggestion has its own bug issue now: https://github.com/transientskp/tkp/issues/512
