### ISSUE TITLE
MonetDB Python api raises OperationalError where IntegrityError is expected

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/tkp#427]

**Comment by timstaley** [comment]
Hey Gijs, I think we already handle this somewhere, although it would be nice to clean it up so we don't have to. Is that what you had in mind (and can you link to the code to remind us) or is it causing problems elsewhere?

**Comment by gijzelaerr** [comment]
Yes, we have a workaround that I have to reimplement using SQLALchemy now. I don't like a workaround, prefer to fix it at the source and let python-monetdb raise the correct error.

**Comment by gijzelaerr** [comment]
Working on this upstream in the new pymonetdb fork:

https://github.com/gijzelaerr/pymonetdb/issues/4

**Comment by gijzelaerr** [comment]
This has been fixed upstream
