### ISSUE TITLE
AARTFAAC data accessor does not provide a consistent model of the data

### ISSUE THREAD

**Issue by timstaley** [transientskp/tkp#444]
Copied here from Hipchat for posterity:

I've just been checking out the unit-test errors from https://github.com/transientskp/tkp/tree/aartfaac-rebase . The remaining failing test was basically telling us that the pixel scale (as parsed by the a
ccessor code) doesn't seem to match up to the distance between two pixels as calculated using the WCS.
At first I thought this might be because our co-ordinate calculations assume small angles, so I shrunk the separate to one pixel / 0.1 degrees. It's still out by a factor of more than 3:

    FAIL: test_pix_scale (test_aartfaaccasatable.TestAartfaacCasaImage)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/home/ts3e11/code/tkp-dev/tkp/tests/test_accessors/test_aartfaaccasatable.py", line 60, in test_pix_scale
    self.assertAlmostEqual(abs(coord_dist_deg), abs(pix_dist_deg), places=6)
    AssertionError: 0.3905301358215481 != 0.11214070992761932 within 6 places

So I did some more digging
and it seems the 'pointing centre' as reported by the accessor doesn't match the co-ordinates displayed for the centre of the image in casaview.
Casaviewer displays the centre as RA, Dec approx 315, +52 [degrees]

But the centre as parsed here: https://github.com/transientskp/tkp/blob/master/tkp/accessors/casaimage.py#L102 
is reported as 118.859, 52.915, so RA is out by about 200 degrees

It would be helpful to know what the correct pixel scale is in that image (is there even a fixed pixel scale across the image?) - so at least then we could figure out which bit of code is reporting correctly
Tim Staley

Anyway, the point is that looking at this closely has revealed it's not a simple issue of checking everything works and updating the relevant fixed values in the unit test - there seems to be a lot of inconsistency in how the TraP accessor is interpreting the AARTFAAC test image, so it needs more work before we can accept it into the master branch, **or** we need a careful examination of why the accessor data-model is not a good fit for AARTFAAC data, and whether this will break other functionality in TraP.

**Comment by gijzelaerr** [comment]
Thanks Tim for having a look at this. Good we have a test that indicates something is wrong here.

**Comment by gijzelaerr** [comment]
This is actually also causing the negative RA values in the TRAP runs of Yvette.

**Comment by gijzelaerr** [comment]
Correction, it was not causing the negative RA values, but it was related. But I think this issue has been resolved now.

**Comment by gijzelaerr** [comment]
so the headers are consistent now, we can close this issue.
