### ISSUE TITLE
Installation instructions for Ubuntu 14.04

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/tkp#446]
To get trap up and running quickly one can use these commands:

```
$ sudo apt-get install software-properties-common
$ sudo add-apt-repository ppa:radio-astro/main
$ sudo apt-get update
$ sudo apt-get install python-numpy python-scipy postgresql python-psycopg2 python-casacore
$ pip install .
```

Also work with Ubuntu 15.04

**Comment by timstaley** [comment]
also ``libpq, wcslib-dev``

**Comment by gijzelaerr** [comment]
not `libpq-dev`?

**Comment by gijzelaerr** [comment]
why `libpq`? isn't that implicitly installed by `postgresql` & `python-psycopg2`?

**Comment by timstaley** [comment]
Ah - you know what, it's my virtualenv rebuilding psycopg2 - that's why it wants the ``-dev`` version. Probably worth adding to the list, for others who want to build in a --no-site-packages virtualenv.

**Comment by gijzelaerr** [comment]
yeah and there we go adding all kind of specific details :)

**Comment by gijzelaerr** [comment]
With the latest pip tkp is much easier and quicker to install.

for a system wide install:
```
$ sudo apt-get install python-pip
$ sudo pip install --upgrade pip
$ sudo apt-get install python-psycopg2 python-casacore  # these still require compilation
$ sudo pip install tkp
```

or for a virtualenv install:
```
$ sudo apt-get install python-pip
$ sudo pip install --upgrade pip
$ sudo apt-get install libboost-python-dev libpq-dev wcslib-dev libcfitsio-dev
$ pip install tkp
```

**Comment by AntoniaR** [comment]
This is now documented.
