### ISSUE TITLE
TraP Crash on AARTFAAC source extraction.

### ISSUE THREAD

**Issue by hsuyeep** [transientskp/tkp#453]
TraP run on a large archival dataset (Database vlo_testcorrectra, dataset 12, ~5000 images) crashes on this image:
http://banana.transientskp.org/master/vlo_testcorrectra/image/2879/.  This can be seen when the number of sources after image 2879 goes to 0 (http://banana.transientskp.org/master/vlo_testcorrectra/images/?page=6&dataset=12). The metadata seems to be extracted correctly for all 5K images, with TraP crashing during source extraction.A part of the error message is:

```
return tkp.steps.source_extraction.extract_sources(url, extraction_params)
  File "/home/peeyush/tkp/tkp/steps/source_extraction.py", line 50, in extract_sources
    force_beam=extraction_params['force_beam']
  File "/home/peeyush/tkp/tkp/sourcefinder/image.py", line 401, in extract
    labelled_data=labelled_data, labels=labels
  File "/home/peeyush/tkp/tkp/sourcefinder/image.py", line 863, in _pyse
    det = extract.Detection(measurement, self, chunk=island.chunk)
  File "/home/peeyush/tkp/tkp/sourcefinder/extract.py", line 754, in __init__
    self._physical_coordinates()
  File "/home/peeyush/tkp/tkp/sourcefinder/extract.py", line 820, in _physical_coordinates
    [self.x.value, self.y.value])]
  File "/home/peeyush/tkp/tkp/utility/coordinates.py", line 668, in p2s
    raise RuntimeError("Spatial position is not a number")
RuntimeError: Spatial position is not a number
```

The p2s is probably caused by the wcs picking a position below the horizon. The failing image is /scratch/peeyush/pipeline/testnewra/2013_try3/F5.76172e+07_S1-63_T20-11-2013_14-42-04.image, but running pyse on this image alone is not a problem:
```
image2fits in=F5.76172e+07_S1-63_T20-11-2013_14-42-04.image/ out=test.fits
image2fits: Version 20090915GvD
The input image is: F5.76172e+07_S1-63_T20-11-2013_14-42-04.image/
2015-08-26 15:03:01	INFO	ImageFitsConverter::ImageToFITS 	Copying '/home/peeyush/F5.76172e+07_S1-63_T20-11-2013_14-42-04.image' to file All pixels fit in memory (1048576 pixels).
image2fits normally ended

(aartfaac_venv)peeyush@struis:~$ pyse.py test.fits 
Processing test.fits (file 1 of 1).
WARNING:tkp.accessors.fitsimage:End time not specified or unreadable
Thresholding with det = 10.000000 sigma, analysis = 3.000000 sigma
** test.fits **

RA: 5.85777+-0.104018, dec: 64.1844+-0.0568066
Error radius (arcsec): 319.133401457
Semi-major axis (arcsec): 2397.63+-225.038
Semi-minor axis (arcsec): 1519.38+-107.749
Position angle: 98.2091+-10.96
Flux: 0.40778+-0.0617844
Peak: 0.47673+-0.038894

RA: 305.477+-0.0408007, dec: 40.3661+-0.0354329
Error radius (arcsec): 178.414123721
Semi-major axis (arcsec): 1998.42+-112.977
Semi-minor axis (arcsec): 1817.74+-89.8041
Position angle: 40.897+-14.3025
Flux: 1.6993+-0.152572
Peak: 1.58394+-0.083709

RA: 253.251+-0.0401218, dec: 5.50871+-0.0690654
Error radius (arcsec): 368.493950042
Semi-major axis (arcsec): 2951.78+-258.214
Semi-minor axis (arcsec): 1461.31+-94.0451
Position angle: 22.3684+-9.67344
Flux: 0.299577+-0.04412
Peak: 0.405085+-0.0303942

RA: 238.151+-0.0888923, dec: -16.4235+-0.154046
Error radius (arcsec): 1115.34904314
Semi-major axis (arcsec): 8391.04+-541.957
Semi-minor axis (arcsec): 6264.44+-353.252
Position angle: 31.3622+-18.3928
Flux: 0.792469+-0.0887733
Peak: 0.956198+-0.0577063
```

**Comment by hsuyeep** [comment]
Another run with a restricted number of images recreates the problem. Note that times are off by 1hr due to some mixup between CET and UTC. The times in the filename is UTC. Looks like the problem is in image F5.76172e+07_S1-63_T20-11-2013_14-42-13.image, not the previous one.  The problem seems to be in the sourcefinder stage, although a standalone pyse run did not generate the error. The problem seems to be in the extract_source.py part (see highlighted part of the error message.) The full error message from TraP is: 

INFO:tkp.main:processing 1 images in timestep 2013-11-20 15:42:04.224959 (16/84)
INFO:tkp.main:performing source extraction
INFO:tkp.distribute.serial.tasks:running extracted sources task
INFO:tkp.distribute.serial.tasks:running extracted sources task
INFO:tkp.steps.source_extraction:Extracting image: /scratch/peeyush/pipeline/testnewra/2013_try3/F5.76172e+07_S1-63_T20-11-2013_14-42-04.image
INFO:tkp.steps.source_extraction:Detected 6 sources in image /scratch/peeyush/pipeline/testnewra/2013_try3/F5.76172e+07_S1-63_T20-11-2013_14-42-04.image
INFO:tkp.main:storing extracted sources to database
INFO:tkp.db.general:Inserted 6 sources in extractedsource for image 7747
INFO:tkp.main:performing database operations
INFO:tkp.main:performing DB operations for image 7747
INFO:tkp.main:performing source association
INFO:tkp.steps.forced_fitting:Found 4 null detections
INFO:tkp.steps.forced_fitting:Forced fitting in image: /scratch/peeyush/pipeline/testnewra/2013_try3/F5.76172e+07_S1-63_T20-11-2013_14-42-04.image
INFO:tkp.steps.forced_fitting:adding null detections
INFO:tkp.db.general:Inserted 4 forced-fit null detections in extractedsource for image 7747
INFO:tkp.steps.forced_fitting:No successful monitor fits
INFO:tkp.main:processing 1 images in timestep 2013-11-20 15:42:13.288321 (17/84)
INFO:tkp.main:performing source extraction
INFO:tkp.distribute.serial.tasks:running extracted sources task
INFO:tkp.steps.source_extraction:Extracting image: /scratch/peeyush/pipeline/testnewra/2013_try3/F5.76172e+07_S1-63_T20-11-2013_14-42-13.image
----------------------------------------
WARNING:tkp.sourcefinder.extract:Physical coordinates failed at 227.023519, 71.433777
WARNING:tkp.sourcefinder.image:Island not processed; unphysical?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
  File "/home/peeyush/aartfaac_venv/bin/trap-manage.py", line 10, in <module>
    execfile(__file__)
  File "/home/peeyush/tkp/tkp/bin/trap-manage.py", line 10, in <module>
    tkp.management.main()
  File "/home/peeyush/tkp/tkp/management.py", line 360, in main
    args.func(args)
  File "/home/peeyush/tkp/tkp/management.py", line 229, in run_job
    run(args.name, monitor_coords)
  File "/home/peeyush/tkp/tkp/main.py", line 145, in run
    extraction_results = runner.map("extract_sources", urls, arguments)
  File "/home/peeyush/tkp/tkp/distribute/__init__.py", line 42, in map
    return self.module.map(func, iterable, args)
  File "/home/peeyush/tkp/tkp/distribute/serial/__init__.py", line 3, in map
    x = [func(i, *arguments) for i in iterable]
  File "/home/peeyush/tkp/tkp/distribute/serial/tasks.py", line 22, in extract_sources
    return tkp.steps.source_extraction.extract_sources(url, extraction_params)
  File "/home/peeyush/tkp/tkp/steps/source_extraction.py", line 50, in extract_sources
    force_beam=extraction_params['force_beam']
  File "/home/peeyush/tkp/tkp/sourcefinder/image.py", line 401, in extract
    labelled_data=labelled_data, labels=labels
  File "/home/peeyush/tkp/tkp/sourcefinder/image.py", line 863, in _pyse
    det = extract.Detection(measurement, self, chunk=island.chunk)
  File "/home/peeyush/tkp/tkp/sourcefinder/extract.py", line 754, in __init__
    self._physical_coordinates()
  File "/home/peeyush/tkp/tkp/sourcefinder/extract.py", line 820, in _physical_coordinates
    [self.x.value, self.y.value])]
  File "/home/peeyush/tkp/tkp/utility/coordinates.py", line 668, in p2s
    raise RuntimeError("Spatial position is not a number")
RuntimeError: Spatial position is not a number

**Comment by hsuyeep** [comment]
Pyse seems quite happy on this image (F5.76172e+07_S1-63_T20-11-2013_14-42-13.image), as can be seen from the screenshot of the detected sources overlaid.
![image](https://cloud.githubusercontent.com/assets/1520321/9498946/bd5a63d0-4c1c-11e5-905d-19065af6c729.png)
The problematic location is marked with a red diamond, and is:
WARNING:tkp.sourcefinder.extract:Physical coordinates failed at 227.023519, 71.433777
WARNING:tkp.sourcefinder.image:Island not processed; unphysical?

**Comment by gijzelaerr** [comment]
I can replicate this problem by running pyse with a detection threshold of 4 on the given image:

```
pyse.py F5e+07_S0-62_T13-08-2015_22-28-27.image --detection 4
Processing F5e+07_S0-62_T13-08-2015_22-28-27.image (file 1 of 1).
Thresholding with det = 4.000000 sigma, analysis = 3.000000 sigma
WARNING:tkp.sourcefinder.extract:Physical coordinates failed at 441.536942, 1034.250397
WARNING:tkp.sourcefinder.image:Island not processed; unphysical?
Traceback (most recent call last):
  File "../tkp/tkp/bin/pyse.py", line 358, in <module>
    print run_sourcefinder(files, options),
  File "../tkp/tkp/bin/pyse.py", line 319, in run_sourcefinder
    force_beam=options.force_beam
  File "/home/gijs/Work/tkp/tkp/sourcefinder/image.py", line 401, in extract
    labelled_data=labelled_data, labels=labels
  File "/home/gijs/Work/tkp/tkp/sourcefinder/image.py", line 863, in _pyse
    det = extract.Detection(measurement, self, chunk=island.chunk)
  File "/home/gijs/Work/tkp/tkp/sourcefinder/extract.py", line 754, in __init__
    self._physical_coordinates()
  File "/home/gijs/Work/tkp/tkp/sourcefinder/extract.py", line 820, in _physical_coordinates
    [self.x.value, self.y.value])]
  File "/home/gijs/Work/tkp/tkp/utility/coordinates.py", line 668, in p2s
    raise RuntimeError("Spatial position is not a number")
RuntimeError: Spatial position is not a number
```

**Comment by gijzelaerr** [comment]
so I've changed the logic a bit so it wont crash, but just generates big fat warnings.

Actually this is very similar to the fix of @mkuiack, but I can't replicate the database problems he had.

**Comment by gijzelaerr** [comment]
I Think this issue has been solved?

**Comment by timstaley** [comment]
@gijzelaerr @hsuyeep - Yeah, I think this may have been fixed by https://github.com/transientskp/tkp/pull/496. You'll need to test with a master-checkout to confirm; I've been meaning to cut a 3.0.1 release but I've been snowed under with other stuff.

**Comment by timstaley** [comment]
Closing this, @hsuyeep feel free to reopen if you test and find it still present.
