### ISSUE TITLE
Implement QC Step for AA Trap

### ISSUE THREAD

**Issue by ycendes** [transientskp/tkp#454]
I have written a simple quality control step for the AARTFAAC branch of Trap to take care of images with a bright RFI source in them, and it would be great if we could implement it into the AARTFAAC-specific TraP so then we can test it out (it should help us reduce the "jumps" we see in the number of sources tracked by flagging out the images with high RFI in them).

The script I wrote is currently available here: https://github.com/transientskp/aartfaac-tools/blob/master/rms-check.py

In short, it automatically flags everything over a certain RMS threshold in our images as these all are associated with RFI.  Currently the threshold is just set at "2", which is ok for a quick and dirty first step but ideally should be something related to the value of the rest of the images, ie sigma clipping (where everything over, say, 2 sigma is flagged out).  Gijs, do you know how to do that simply from your end?  I've been trying to get a histogram thing to work today, but am busy with proposals too so haven't gotten it to work just right. :(

In short though, if sigma clipping is too difficult just make it flag everything above 2 for now and we can update later once I figure out how the code should work.

**Comment by AntoniaR** [comment]
Unfortunately I can't seem to find your code when I follow the link - I assume some github privacy thing (would it be possible to be added to that repository?).

But if you have the code to get the RMS (great :D) then you could simply use the code that I developed and discussed with you a while back... The one that fits a Gaussian, clips to a certain sigma (user defined) and then creates the images_to_process.py file for TraP. Basically, this code does exactly what you're after! My intention is to get something like this into TraP but it's a good standalone tool for now which works really well with the current TraP setup.

The code is here: https://github.com/AntoniaR/scripts/tree/new_QC/TraP_fits_QC

In particular, the fitting is in this code https://github.com/AntoniaR/scripts/blob/new_QC/TraP_fits_QC/tools.py
You could either call the function by copying the tools script (you'll need almost all of the functions in that script) into your repository and then add the following to your code:
```
import tools

noise_avg, noise_scatter, noise_threshold =  tools.fit_hist(data, sigma, xlabel, pltname, freq)

thresholds=[noise_avg,noise_scatter*sigmaRej,noise_scatter*sigmaRej*-1.]
```
This creates a plot of the data with a fitted Gaussian and returns the numbers you need to filter the data.
The inputs are:
* "data" : a 1D list of data points
* "sigma" : the sigma threshold that you want to clip
* "xlabel" : the x-axis label for the plot - i.e. "RMS noise (Jy)"
* "pltname" : the string which is used to name the output figure
* "freq" : the observing frequency used in output figure filename and plot (not important so you could add anything here, but nice info)
* noise_avg : the mean of the fitted Gaussian
* noise_scatter : the 1sigma errors
* noise_threshold : the 1sigma errors * sigma - i.e. the threshold to clip above and below your distribution.

An example of this use is in my script here: https://github.com/AntoniaR/scripts/blob/new_QC/TraP_fits_QC/TraP_fits_QC.py#L55-63 where I fit the RMS noise in logarithmic space and then write out the mean and 1 sigma errors (it's up to you whether you fit in linear or log space - whatever works best for AARTFAAC data). The rest of the script has a range of different options that should be reasonably documented but probably of less use to you.

Later in the code, I then loop through all the images to figure out if their RMS is within the noise thresholds using something like (where the image data is in an array with columns: image name, freq, RMS):
```
for image in imageData:
    if image[2]<thresholds[0]+thresholds[1] and image[2]>thresholds[0]+thresholds[2]:
        goodImg.append(image[0])
    else:
        print 'Bad image:',image[0],image[1],image[2],image[3]
```
The good images are then written out into the images_to_process.py file here https://github.com/AntoniaR/scripts/blob/new_QC/TraP_fits_QC/TraP_fits_QC.py#L101-L113

Hopefully that makes sense and you're able to implement it in your code. I can probably give more direct help if given access to the repository... Alternatively, if it can wait 1 month, I will be able to help in person... :)

**Comment by ycendes** [comment]
Hi Antonia,

The script is currently in our "aartfaac-tools" folder which is private.  Can't figure out how to add you in so maybe @hsuyeep can add you?

But basically to get you up to speed, we need at least some QC stuff now (can't wait a month, unfortunately) so I played around with it, and it turns out *all* images with a high background RMS value have an RFI source in the northeast of the image.  So Gijs kindly agreed to add such a step to AARTFAAC-TraP so we can start skipping over those images and the problems they cause.  We'll see how it goes!

**Comment by gijzelaerr** [comment]
The QC Yvette wrote is very simpel but should work for now. Basically it
rejects images with an global RMS value above 2. We will replace this in
the future with more advanced QC logic, but then now Yvette can continue.

Will add the test on monday, now listening to talks @ euroscipy.

2015-08-28 10:34 GMT+01:00 ycendes <notifications@github.com>:

> Hi Antonia,
>
> The script is currently in our "aartfaac-tools" folder which is private.
> Can't figure out how to add you in so maybe @hsuyeep
> <https://github.com/hsuyeep> can add you?
>
> But basically to get you up to speed, we need at least some QC stuff now
> (can't wait a month, unfortunately) so I played around with it, and it
> turns out *all* images with a high background RMS value have an RFI
> source in the northeast of the image. So Gijs kindly agreed to add such a
> step to AARTFAAC-TraP so we can start skipping over those images and the
> problems they cause. We'll see how it goes!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transientskp/tkp/issues/454#issuecomment-135714543>.
>



-- 
Gijs Molenaar
http://pythonic.nl

**Comment by gijzelaerr** [comment]
@ycendes  I was thinking about this, and since it is a more of a temporary solution I think it is better to put this in your `images_to_process.py`. This gives you more control over the testing and evaluation.

You can filter the list of images to process by running the RMS check and removing them from the list or build up a list of images that only pass the RMS test.

**Comment by gijzelaerr** [comment]
@ycendes agrees that this a good idea, she will implement it in her `images_to_process.py` file and we will not do this in TraP for now.
