### ISSUE TITLE
setup TraP & banana demo server

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/tkp#460]
for this we need one of more datasets that are pretty and can be made public

**Comment by gijzelaerr** [comment]
@timstaley mentioned a gamma ray Burst dataset that looks pretty.

@bartscheers mentioned the NCP dataset, although @ajstewart thinks this dataset is not pretty.

**Comment by timstaley** [comment]
Yep - GRB140327A, cf https://fourpisky.files.wordpress.com/2014/09/figure2.png makes a nice, simple, easy-to-understand dataset. I use it for testing basic functionality.

**Comment by gijzelaerr** [comment]
@timstaley where do i find this dataset? can you move it to struis? 

Is it an idea to use it for a nightly jenkins performance test? something is better than nothing.

**Comment by timstaley** [comment]
https://github.com/timstaley/trap-demo-data

**Comment by gijzelaerr** [comment]
ok, maybe just our latest AARTFAAC dataset then, that is about 1377 images, we can always change the dataset.

**Comment by AntoniaR** [comment]
Banana will not be developed further so not required.
