### ISSUE TITLE
'spectral1' error when running AARTFAAC images

### ISSUE THREAD

**Issue by ycendes** [transientskp/tkp#464]
Just tried to run a new batch of AARTFAAC images (at /scratch/fhuizing/aartfaac/results/shower/s256) through TraP, and get an error when I try to do so.  All I get as an error is KeyError: 'spectral1'

**Comment by mkuiack** [comment]
You can change 'spectral1' to 'spectral2' in aartfaaccasaimage.parse_frequency

**Comment by gijzelaerr** [comment]
this issue has been resolved
