### ISSUE TITLE
one failed db test makes all db tests fail

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/tkp#471]
Since we switched to SQLALchemy when one database test fails all following db tests will also fail. This is because a SQLAlchemy session needs to be rolled back after a failed query. The backwards compatibility code creates a session which is reused for all the tests. if this session fails, it needs to be rolled back at the end of a test set. For the wrapping code it is impossible to determine when it should be rolling back though.

To solve this we need to be more explicit in the all the tests, do a manual rollback _or_ create a new session per test.

**Comment by timstaley** [comment]
Possibly we can use 'nested transactions' for this, at least when testing against Postgres, cf https://github.com/timstaley/voeventcache/blob/master/voeventcache/tests/fixtures/connection.py#L53

**Comment by AntoniaR** [comment]
This issue will likely be resolved in the new redesign of the source association and other SQL commands in TraP R7. Closing this issue.
