### ISSUE TITLE
initdb for monetdb fails

### ISSUE THREAD

**Issue by bartscheers** [transientskp/tkp#473]
As soon as the schema is created ("trap"), we should switch to it, by adding the statement
SET SCHEMA "trap";
in the set_monetdb_schema() function of populate.py 
https://github.com/transientskp/tkp/blob/master/tkp/db/sql/populate.py#L147

**Comment by gijzelaerr** [comment]
hm, for me it is working.

TraP is reconnecting and then using the schema:

https://github.com/transientskp/tkp/blob/master/tkp/db/sql/populate.py#L192

not really an issue if you ask me.

**Comment by bartscheers** [comment]
How do you set your TKP_DBNAME? When you set it to testdb and user/pw as well, it fails. Only when you set it to trap it succeeds, but you want more flexibility than that.

**Comment by gijzelaerr** [comment]
I tried it yesterday and I just set it to `gijs`.

**Comment by timstaley** [comment]
Hey Bart, just in case (this tends to catch me out), you've done the usual:

    monetdbd set control=yes ${dbfarm}
    monetdbd set passphrase=${mypassphrase} ${dbfarm}

Right?

**Comment by bartscheers** [comment]
Correct

**Comment by timstaley** [comment]
And you're specifying the test-database details via the environment variables? cf 
https://github.com/transientskp/tkp/blob/master/tests/runtests.sh#L6 , but when you're running trap-manage, e.g.
   
    TKP_DBNAME=testdb   trap-manage.py initdb

**Comment by bartscheers** [comment]
Yes, indeed. I set all the environment variables, TKP_DBNAME, TKP_DBPORT etc. And when running the trap-manage.py I get 

```
INFO:tkp.db.database:connecting to database...
processing functions/degrad.sql
...
sqlalchemy.exc.OperationalError: (pymonetdb.exceptions.OperationalError) CREATE FUNCTION: name 'degrees' (double(53)) already in use
```

meaning it is trying to create the functions in the sys schema, where they already exists (but not in the trap schema).

Apparently it is in the same session but did not switch schemas.

**Comment by gijzelaerr** [comment]
isn't it already populated? Did you do a destroy and create before init?


2015-09-25 17:27 GMT+02:00 Bart Scheers <notifications@github.com>:

> Yes, indeed. I set all the environment variables, TKP_DBNAME, TKP_DBPORT
> etc. And when running the trap-manage.py I get
>
> INFO:tkp.db.database:connecting to database...
> processing functions/degrad.sql
> ...
> sqlalchemy.exc.OperationalError: (pymonetdb.exceptions.OperationalError) CREATE FUNCTION: name 'degrees' (double(53)) already in use
>
> meaning it is trying to create the functions in the sys schema, where they
> already exists (but not in the trap schema).
>
> Apparently it is in the same session but did not switch schemas.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transientskp/tkp/issues/473#issuecomment-143252082>.
>



-- 
Gijs Molenaar
http://pythonic.nl

**Comment by bartscheers** [comment]
No, not populated. Yes, I created it and the user. Creation of the schema is left to populate.py.

**Comment by gijzelaerr** [comment]
fixed per https://github.com/transientskp/tkp/pull/475
