### ISSUE TITLE
test_alchemy fails for monetdb

### ISSUE THREAD

**Issue by bartscheers** [transientskp/tkp#476]
Some tests do fail for MonetDB because in the current trap schema the SQL function median() is called, instead of the sys.median() function.

**Comment by bartscheers** [comment]
See discussio/approach in https://github.com/transientskp/tkp/pull/482

**Comment by AntoniaR** [comment]
MonetDB has been retired from TraP.

This issue will likely be resolved in the new redesign of the source association and other SQL commands in TraP R7. Closing this issue.
