### ISSUE TITLE
add continuous image input mode

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/tkp#483]
Currently we only support processing datasets in batch (fixed size dataset) mode. Since AARTFAAC produce images in a continues mode, we need to add logic to TraP to handle this.

A simple hackish approach could be to let the AARTFAAC imager write the images to a folder and let TraP run on the same system. TraP Would monitor this folder and process a time step as soon as all subbands are written to disk. 

There are some problems with this approach though. Reading and writing to disk is just very slow. Also the headers need to be written and parsed for for every image, introducing significant slowdowns. Also TraP and the imager need to be running on the same system or share a filesystem over for example NFS.

Probably a better approach would be to work with a network based publisher - subscription model, where the AARTFAAC imager 'publishes' a image producing service on the network. TraP could then connect to this service and subscribe to a stream of images. The format of these images and headers need to be defined, but ideally no reinterpretation is required and a raw (python-)casacore table can be written to memory and interpreted by the TraP accessor logic. 

Some sort of caching would be required also, we want to only start process a timestep when all images within a datacube (all subbands for a given timestep) are received.

So biggest open question here is how do we move a in memory casatable over the network from the imager to the TraP.

**Comment by gijzelaerr** [comment]
Working with @Error323 on this as we speak. We are making a binary wire protocol based on FITS headers.

**Comment by timstaley** [comment]
You might find this of interest, although it's still at beta stage: http://pyasdf.readthedocs.io/en/latest/
Effectively a FITS file, but the fixed width ASCII header is replaced by YAML.

**Comment by gijzelaerr** [comment]
interesting. But for now we already started working on a fits implementation, since we just want to get this working and it has Python and C++ support. The protocol supports new versions, so we may think about switching in the future, but for now we do this.

**Comment by gijzelaerr** [comment]
related github repo https://github.com/transientskp/aartfaac-output-simulator

**Comment by gijzelaerr** [comment]
we have first contact https://github.com/transientskp/notebooks/blob/master/AARTFAAC%20TraP%20interface.ipynb

**Comment by gijzelaerr** [comment]
https://github.com/transientskp/tkp/pull/515

**Comment by gijzelaerr** [comment]
active development is in this branch https://github.com/transientskp/tkp/tree/aartfaac-stream which depends on this PR https://github.com/transientskp/tkp/pull/515

**Comment by gijzelaerr** [comment]
@mkuiack I think this one is ready for review. This PR also contains other bug fixes.

For evaluating the streaming support you need to set up a face AARTFAAC streamer. You can do this on struis:

```
$ ssh struis -L 6666:localhost:6666 -L 6667:localhost:6667 -L 6668:localhost:6668 -L 6669:localhost:6669
$ export FPS=1
$ /home/fhuizing/aartfaac-output-simulator/build/aartfaac-output-simulator -input /scratch/gijs/aartfaac_with_subbands/S296 -fps ${FPS} -port 6666 &
$ /home/fhuizing/aartfaac-output-simulator/build/aartfaac-output-simulator -input /scratch/gijs/aartfaac_with_subbands/S297 -fps ${FPS} -port 6667 &
$ /home/fhuizing/aartfaac-output-simulator/build/aartfaac-output-simulator -input /scratch/gijs/aartfaac_with_subbands/S298 -fps ${FPS} -port 6668 &
$ /home/fhuizing/aartfaac-output-simulator/build/aartfaac-output-simulator -input /scratch/gijs/aartfaac_with_subbands/S300 -fps ${FPS} -port 6669 &
````

This will start 4 AARTFAAC emulators on the ports 6666 to 6669, while your SSH connection is exposing this on your local system. You need to configure TraP into 'streaming' mode in the job config ,with the correct hostnames and ports. The job template has been updated.

**Comment by mkuiack** [comment]
Variablity Metrics are not being calculated in stream mode. 

http://banana.transientskp.org/master/vlo_mark_stream/varmetric/?dataset=6

**Comment by gijzelaerr** [comment]
is this only for stream mode or also for batch mode?

**Comment by mkuiack** [comment]
batch mode crashed with 

RuntimeError: BucketCache::getBucket: bucket 29 exceeds nr of buckets

**Comment by gijzelaerr** [comment]
the batch mode error was caused by a faulty casacore table, bug has been reported upstream https://github.com/casacore/python-casacore/issues/69. The variability metrics are correctly calculated, this was probably a human @mkuiack error somewhere.

This PR has been merged, we are good to go!
