### ISSUE TITLE
Documentation needed for monitoring locations in TraP

### ISSUE THREAD

**Issue by ycendes** [transientskp/tkp#485]
Right now, there does not appear to be any documentation for monitoring specific locations while TraP is running (ie, trap-manage.py run database, specify "also keep an eye at these coordinates" or similar).  Antonia and I have checked for it on the TraP documentation page, the TraP for dummies guide on the LOFAR wiki, and the documentation on this GitHub page, but have not found anything.

**Comment by timstaley** [comment]
http://tkp.readthedocs.org/en/release2.1/userref/trap-manage.html
(Under 'run') 
But I agree it's totally minimal, non-obvious, and could use improvement.
