### ISSUE TITLE
Number of forced fits not always correct

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/tkp#493]
original issue reported here

https://github.com/transientskp/banana/pull/102

**Comment by gijzelaerr** [comment]
i'm tempted to just replace with with a count() and remove the manual administrated column which somewhere has a mistake in the SQL spagetti. @timstaley what do you think?

**Comment by gijzelaerr** [comment]
to clarify, I think the forcedfits_count column  is an example of premature optimization.

**Comment by AntoniaR** [comment]
This issue will likely be resolved in the new redesign of the source association and other SQL commands in TraP R7. Closing this issue.
