### ISSUE TITLE
Missing documentation on monitoring list parameters

### ISSUE THREAD

**Issue by hsuyeep** [transientskp/tkp#498]
If one wants to run trap with a monitoring list, the documentation is not clear on the units of the position of the source to be monitored. trap-manage.py run -h gives:
  -m MONITOR_COORDS, --monitor-coords MONITOR_COORDS
                        a list of RA,DEC coordinates to monitor in JSON format, example: [[5, 6], [7, 8]]
  -l MONITOR_LIST, --monitor-list MONITOR_LIST
                        Specify a file containing a list of RA,DEC

Also, the pages at 
http://tkp.readthedocs.org/en/latest/userref/trap-manage.html
and http://tkp.readthedocs.org/en/r3.0/getstart/index.html  don't seem to have the units defined anywhere.

**Comment by gijzelaerr** [comment]
what would you like it to say?

**Comment by hsuyeep** [comment]
Something along the lines of "Coordinates to be specified in degrees." would certainly help.

**Comment by gijzelaerr** [comment]
So you are sure the coordinates need to be specified in degrees?

**Comment by hsuyeep** [comment]
yes.

**Comment by timstaley** [comment]
NB Dupes #485
