### ISSUE TITLE
Add info to output on "trap-mange.py run" failure

### ISSUE THREAD

**Issue by brianalden** [transientskp/tkp#501]
When running trap-manage.py run on a dataset, if it fails because of a faulty image or lack of metadata, the error output is something like the following:
```
Traceback (most recent call last):
  File "/soft/trap/nightly/a846b89/bin/trap-manage.py", line 5, in <module>
    pkg_resources.run_script('tkp==3.0', 'trap-manage.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
INFO:tkp.distribute.multiproc.tasks:running persistence task
    execfile(script_filename, namespace, namespace)
  File "/soft/trap/nightly/a846b89/lib/python2.7/site-packages/tkp-3.0-py2.7.egg/EGG-INFO/scripts/trap-manage.py", line 10, in <module>
    tkp.management.main()
  File "/soft/trap/nightly/a846b89/lib/python2.7/site-packages/tkp-3.0-py2.7.egg/tkp/management.py", line 323, in main
    args.func(args)
  File "/soft/trap/nightly/a846b89/lib/python2.7/site-packages/tkp-3.0-py2.7.egg/tkp/management.py", line 223, in run_job
    run(args.name, monitor_coords)
  File "/soft/trap/nightly/a846b89/lib/python2.7/site-packages/tkp-3.0-py2.7.egg/tkp/main.py", line 102, in run
    [image_cache_params, rms_est_sigma, rms_est_fraction])
  File "/soft/trap/nightly/a846b89/lib/python2.7/site-packages/tkp-3.0-py2.7.egg/tkp/distribute/__init__.py", line 42, in map
    return self.module.map(func, iterable, args)
  File "/soft/trap/nightly/a846b89/lib/python2.7/site-packages/tkp-3.0-py2.7.egg/tkp/distribute/multiproc/__init__.py", line 23, in map
    return pool.map(func, zipped)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
KeyError: 'LOFAR_FIELD'
```

The problem with that is that you just know there is an error, but not which file caused it. Further, as it is running multithreaded, one cannot just trace through the output and see what the last file processed was. In the current codebase, I don't believe there is any way of knowing which file caused the failure.

A simple addition of outputting the filename that caused the failure would make troubleshooting remarkably easier.

**Comment by gijzelaerr** [comment]
What telescope data are you using? You need to **or** inject the meta data into the headers of the images **or** add an Accessor for your specific telescope (not that hard).

We do support a serial mode for problems like this:

http://tkp.readthedocs.org/en/latest/userref/config/pipeline_cfg.html#parallelise-section

I now see that the documentation is lacking the 'serial' option. Please try again with this settings.

**Comment by AntoniaR** [comment]
Gijs - I believe these are LOFAR images but Brian can confirm.
Brian, are you using LOFAR casa images or LOFAR fits images?
If Casa, then the metadata should be already injected and you do not need to follow the inject instructions from Gijs. You should've run a script which injects the metadata into the CASA image from the measurement set as a final stage in imaging (Alexander has the instructions). If that script has been run and you get an error with the Casa images, then there is a bug in TraP.
If LOFAR Fits, my first question is why not Casa? Otherwise, you need to inject the correct metadata using tkp-inject - which should be documented in the TraP documentation.

**Comment by brianalden** [comment]
I am running TraP on LOFAR images generated with awimager. I believe it is using Casa. After generating the images with awimager, I then run the addImagingInfo script on each of the files. This works 99% of the time. Sometimes though, I find that the process failed and maybe 1 image in 500 will have an error in the metadata. I feel like this is likely due to the script not running completely. I don't necessarily think there is a fault in the script, but for example I have had a connection drop in the middle of running a large batch of addImagingInfo commands. I am assuming that when the script stops without completion, the image it was working on is then corrupted. Running the TraP serially as opposed to in parallel would give me the the desired effect as I would then know exactly which file is at fault.

**Comment by AntoniaR** [comment]
Yes, this sounds like an addimaginginfo issue, which is LOFAR software so not something we have control over. If there is a bug in addimaginginfo, we can report it to the LOFAR Radio Observatory and attempt to get it fixed.

However, as you say, it sounds like unusual cases where the metadata fails to add. Then we have 2 choices: 1. track down the images by running TraP in serial and seeing where it fails (time consuming but would help you identify cause and potentially fix it) or 2. introduce a new TraP quality control test that rejects the bad images but doesn't cause TraP to crash.

I'm inclined to suggest a combination of both. i.e. you try to fix your metadata as you don't want to reject good images but also make it that TraP will still run without the images (and ideally put the reject reason into the images table on Banana).

Could you identify a small subdataset of say 10 images containing a mix of good and bad? If they are in a folder somewhere on Struis, we can reproduce your error and investigate a new TraP quality control test.

While that test is in development, you run TraP in series by changing the parallelise method in the pipeline.cfg file (see docs here: http://tkp.readthedocs.org/en/r3.0/userref/config/pipeline_cfg.html)

**Comment by timstaley** [comment]
Hi @brianalden  - can you try this again with the latest release (version 3.1.0)?

Suggest you run with serial processing mode, i.e. set
```ini
[parallelise]
method = "multiproc"  ; or serial
```
in *pipeline.cfg*. You'll also need to add the new 
```
[logging]
colorlog = True
```
entry.
In multiprocessing mode we lose log messages from the other processes, which is unhelpful and something to bear in mind when debugging.

Hopefully the reworked logging is helpful in tracking down your issue. Note that trap will also output logfiles to '<jobdir>/logs/<datestamp>' which can be useful - we now output both regular and 'debugging' versions.

**Comment by timstaley** [comment]
Closing this - Brian, please re-open (or file anew) if you re-encounter the issue.
