### ISSUE TITLE
When pip installing tkp it says "setup hook hooks.pywcs_hook raised exception"

### ISSUE THREAD

**Issue by HannoSpreeuw** [transientskp/tkp#506]
Trying to pip install tkp on my Fedora 22 machine:

[root@localhost ~]# pip install tkp
Collecting tkp
  Using cached tkp-3.1.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): astropy in /usr/lib64/python3.4/site-packages (from tkp)
Collecting colorlog (from tkp)
  Using cached colorlog-2.6.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.3.0 in /usr/lib64/python3.4/site-packages (from tkp)
Collecting psycopg2 (from tkp)
  Using cached psycopg2-2.6.1.tar.gz
Collecting python-casacore (from tkp)
  Downloading python-casacore-2.1.2.tar.gz (90kB)
    100% |████████████████████████████████| 92kB 7.0MB/s 
Requirement already satisfied (use --upgrade to upgrade): python-dateutil>=1.4.1 in /usr/lib/python3.4/site-packages (from tkp)
Requirement already satisfied (use --upgrade to upgrade): pytz in /usr/lib/python3.4/site-packages (from tkp)
Collecting pywcs>=1.12 (from tkp)
  Downloading pywcs-1.12.tar.gz (2.0MB)
    100% |████████████████████████████████| 2.0MB 731kB/s 
    Complete output from command python setup.py egg_info:
    
    Installed /tmp/easy_install-noo71t6c/stsci.distutils-0.3.7/.eggs/d2to1-0.2.12.post1-py3.4.egg
    
    Installed /tmp/pip-build-2ktp5ask/pywcs/.eggs/stsci.distutils-0.3.7-py3.4.egg
    Searching for d2to1>=0.2.3
    Reading https://pypi.python.org/simple/d2to1/
    Best match: d2to1 0.2.12.post1
    Downloading https://pypi.python.org/packages/dc/bd/eac45e4e77d76f6c0ae539819c40f1babb891d7855129663e37957a7c2df/d2to1-0.2.12.post1.tar.gz#md5=1ba7e64ead23cbf104993122f0871030
    Processing d2to1-0.2.12.post1.tar.gz
    Writing /tmp/easy_install-x8o4v_ri/d2to1-0.2.12.post1/setup.cfg
    Running d2to1-0.2.12.post1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-x8o4v_ri/d2to1-0.2.12.post1/egg-dist-tmp-tyktnb81
    creating /tmp/pip-build-2ktp5ask/pywcs/.eggs/d2to1-0.2.12.post1-py3.4.egg
    Extracting d2to1-0.2.12.post1-py3.4.egg to /tmp/pip-build-2ktp5ask/pywcs/.eggs
    
    Installed /tmp/pip-build-2ktp5ask/pywcs/.eggs/d2to1-0.2.12.post1-py3.4.egg
    setup hook hooks.pywcs_hook raised exception: 'ascii' codec can't decode byte 0xc2 in position 52: ordinal not in range(128)
    
    Traceback (most recent call last):
      File "/tmp/pip-build-2ktp5ask/pywcs/.eggs/d2to1-0.2.12.post1-py3.4.egg/d2to1/util.py", line 182, in cfg_to_args
        hook_fn(config)
      File "/tmp/pip-build-2ktp5ask/pywcs/hooks.py", line 12, in pywcs_hook
        adjust_compiler()
      File "/tmp/pip-build-2ktp5ask/pywcs/hooks.py", line 180, in adjust_compiler
        output = process.communicate()[0].strip().decode('ascii')
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 52: ordinal not in range(128)
    
    error in setup command: Error parsing /tmp/pip-build-2ktp5ask/pywcs/setup.cfg: SystemExit: 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2ktp5ask/pywcs/

Anyone tried a tkp pip install on a Fedora/Red Hat machine?

**Comment by gijzelaerr** [comment]
Please try to update Pip first (Pip install --upgrade Pip)
Op 4 mei 2016 3:52 p.m. schreef "Hanno Spreeuw" <notifications@github.com>:

**Comment by HannoSpreeuw** [comment]
I did so and no effect.

**Comment by timstaley** [comment]
Hi @HannoSpreeuw! Unfortunately we don't support Python 3 as yet ( I see from your logs that you're on 3.4).

**Comment by HannoSpreeuw** [comment]
I those 3.4s appearing indeed. Still not sure how this happened, because 
_[root@localhost tkp]# which pip
/bin/pip
[root@localhost tkp]# which python
/bin/python
[root@localhost tkp]# python
Python 2.7.10 (default, Sep 24 2015, 17:50:09) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
[root@localhost tkp]# python3
Python 3.4.2 (default, Jul  9 2015, 17:24:30) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
_
So _python_ is python 2.7.10

**Comment by gijzelaerr** [comment]
ah right, well spotted. The documentation stated that only python 2.7 is supported:

http://tkp.readthedocs.io/en/latest/getstart/installation.html#core-dependencies

Plan is to do this in the long run:

https://github.com/transientskp/tkp/issues/371

We first had to fix python-casacore for that, which now has python3 support:

https://github.com/casacore/python-casacore/tree/v2.1.0

But unfortunatly for now this has low priority.

Closing this issue.

**Comment by timstaley** [comment]
@HannoSpreeuw  That is odd - I'm not a Fedora user so don't have any suggestions unfortunately. However, you might consider installing into a virtualenv - you can specify the Python version with the '-p' flag e.g. ```virtualenv  foopy2env -p python2```

**Comment by gijzelaerr** [comment]
yes same here, not sure how this works for fedora. Also not sure how you installed pip, but it looks like it is the python3 pip. you can also try `pip2`, maybe that is the python2 version of pip.

**Comment by HannoSpreeuw** [comment]
_pip2 install tkp_
gives the same error.

**Comment by timstaley** [comment]
Hmmm... looks like an issue with pywcs, rather than the TKP package itself. Maybe try installing the pywcs package separately first to see if you get the same error?

**Comment by timstaley** [comment]
@HannoSpreeuw if you want a relatively hassle free option you could try the virtual machine approach, see https://github.com/timstaley/trap-demo

**Comment by gijzelaerr** [comment]
Just for information, we replaced pywcs with astropy in the upcoming 4.0 release. Although we couldn't replicate this problem I think this should solve the issue.

**Comment by HannoSpreeuw** [comment]
Thanks
