### ISSUE TITLE
Review SQLalchemy / SQL columns naming

### ISSUE THREAD

**Issue by timstaley** [transientskp/tkp#508]
Before the next major release we should quickly review how our SQLAlchemy models match up to the SQL column names. Currently, the `Rejection` model class has a `.rejectreason_id` attribute which refers to the SQL col _rejectreason_, and a `.rejectreason` attribute which is used as the SQLAlchemy relationship mapping to the `Rejectreason` model. 

Confusing, but easily fixed by renaming the SQL column to _rejectreason_id_ to match the model attribute. We should check for similar clashes that could be fixed by a simple rename.

**Comment by gijzelaerr** [comment]
if I remember correctly I did this intentional. What is actually the problem?

**Comment by timstaley** [comment]
No particular problem - it's just extremely confusing! I can see why you did it, presumably to match the previous column naming scheme. But we might as well align the attribute names / column names in the next major release.

**Comment by gijzelaerr** [comment]
so you want to rename all SQL columns from ``<foreign table name>`` ``<foreign table name>_id`` ?

Before SQLAlchemy I didn't like that since it would make many columns 3 characters longer, but maybe it makes sense now.

**Comment by timstaley** [comment]
Yep, basically :) I agree there's no point normally, but I think it makes sense when you're using SQLAlchemy.

**Comment by AntoniaR** [comment]
This issue will likely be resolved in the new redesign of the source association and other SQL commands in TraP R7. Closing this issue.
