### ISSUE TITLE
Revise calculation of 'worst rms'

### ISSUE THREAD

**Issue by ajstewart** [transientskp/tkp#516]
Apologies if this is already recorded as an issue, I had a look but couldn't see it.

As stated [here](http://tkp.readthedocs.io/en/latest/devref/tkp/database/association.html#tkp.db.associations._determine_newsource_previous_limits), currently the 'worst rms' is currently calculated from the same image identified as containing the 'best rms'. I'm wondering if it's worth considering implementing a 'more correct' calculation of the worst rms, the same way the best rms is calculated.

I think the assumption is actually pretty good, but sometimes it's useful to also analyse 'deep' images as part of the images processed. This means that the worst rms suddenly becomes unrealistic as it's obtained from the deep image, which has a very low rms all round. I'm also starting to use datasets that do not have a consistent rms level across the images.

If it wouldn't impact performance too much, perhaps it's worth considering?

**Comment by timstaley** [comment]
Hey Adam - we actually still want the 'worst rms' to come from the deep image, in your example, because it's a threshold that tells us if we expect to have seen a steady-source previously. So if the source is brighter than that 'worst-case RMS' by a significant margin, then we should *definitely* have seen it in the deep image, if it was a regular steady source. Make sense? I should probably expand the docs on this count since we keep coming back to it (and I had to re-read the code recently to remind myself).

**Comment by ajstewart** [comment]
I see what you're saying but I'm still not completely sure it's the best way to go about it.

If you put a deep image through, then what you're essentially saying is here is a deep priori source catalogue for the source association to use. Then in the actual images you are searching if a new source pops up, it should be associated to the source already extracted from the deep image. I see this exactly happen in my VLA dataset as the total number of new sources is reduced by 45%. To me that is the information you need already there, this source was not above your detection threshold in the deep image.

Ok, it is then useful to know if the sigma of the worst part of the deep image is higher than the detection threshold, that I agree with. As you say, you're checking if you definitely shouldn't have seen it. But at the same time I think you still want that worst rms information from the main images you are checking. This stems from the fact that when I run a manual analysis using Antonia's definition of comparing the worst_rms_sigmas, all my transient candidates are defined as likely transients, making the separation between likely and possibly redundant.

This I reckon is starting to move onto 'how to handle a deep image', but if the deep image scenario is ignored, it think it becomes even more important. If I run the dataset through without the deep image, then the worst and best assumption breaks down a bit as my images can vary quite a lot from 20uJy to below 10uJy which is relatively a significant difference, but are all still good images (of course you have to assume that the quality control has been done on the images, otherwise you'll end up with the opposite scenario as above where all will be possibly transients). Even just to know the true best and worst rms of the dataset seems very useful.

If you are going to make this assumption that I should have definitely seen it before (or I guess again, depending where the best or worst images lie in the timeline) in the dataset, then you need to use the worst rms of the worst image to make this more definitive. At the moment if I were to do a search, I can't say the statement of 'I would have seen it even at the worst rms of the other images.' - which in my opinion is the more useful statement to make.

It's confusing to know which gives the best information, I keep switching back and forth in my mind about it. Maybe I'm failing to consider some aspect, but ignoring the whole deep image scenario I think it's important to obtain the 'correct' worst_rms from the dataset. If it remains though, it needs to be made clear as before I dug into the docs a while ago, I always assumed it was the worst rms of the dataset and was surprised to see it wasn't.

**Comment by timstaley** [comment]
Hi Adam,

I'm not sure if we're talking across purposes here - it might be useful to know the 'worst-image worst RMS' for judging general data-quality etc, I concur.  But for determining whether a source is a steady source or not, it's no help. Imagine you have an image where the RMS is higher than the flux of all the sources in the field. That bad image then doesn't tell you anything about whether a source is transient or not, because, well, it doesn't tell you anything in general. Right? Maybe this is best discussed with a whiteboard next time you're around Oxford, if that's anytime soon?

**Comment by AntoniaR** [comment]
Hi Adam. I'm completely with Tim here. For confirming whether something is a transient or not, we simply need to know could it have ever been seen before. i.e. we only need to consider the best image and this is even more true for the deep images that you refer to (I used this method in my MWA paper). But in the best image there are good/bad regions and hence we want to compare to the RMS in those regions.

**Comment by ajstewart** [comment]
Yep ok, I was getting confused I think between two different questions:
* is the transient a steady source?
* could the transient have been seen before?

Just seeing if it's a steady source then yes, the best image's worst rms is fine as if there is not a source there then there is not a source there, no need to look any further. The second question is literally related to the transient and not really asking if it's a 'steady source', so that's where my confusion was.
