### ISSUE TITLE
Storing images causes TraP to crash and hang (not exit). 

### ISSUE THREAD

**Issue by mkuiack** [transientskp/tkp#530]
In batch mode with copy_images = True

```python
14:54:30 INFO tkp.main: dataset batch1/ contains 3526 images
14:54:30 INFO tkp.main: Storing copy of images in MongoDB
terminate called after throwing an instance of 'casa::AipsError'
  what():  FiledesIO /scratch/gijs/aartfaac_with_subbands/S301/S301_R0-62_T02-06-2016_21-27-41.image/table.f0_TSM0is not writable
```

**Comment by gijzelaerr** [comment]
this is a casacore issue also. Opening this MS with python-casacore outside of TraP gives this error also.

**Comment by gijzelaerr** [comment]
actually there are 2 issues here, one with casacore crashing, and TraP not handling the crash properly. the first one I will report upstream tomorrow, te second one is a lower priority issue.

**Comment by gijzelaerr** [comment]
I can replicate this on struis but not on my system. I assume this has to do with struis still having casacore 2.0.3 while my system runs 2.1.0.

```
import casacore.images
x = casacore.images.image('/scratch/gijs/aartfaac_with_subbands/S301/S301_R0-62_T02-06-In
x.tofits('bla')
terminate called after throwing an instance of 'casa::AipsError'
  what():  FiledesIO /scratch/gijs/aartfaac_with_subbands/S301/S301_R0-62_T02-06-2016_21-27-41.image/table.f0_TSM0is not writable
```

**Comment by gijzelaerr** [comment]
This was an issue with that specific file on struis, something went wrong during copying. I replaced it with the right one. I'll close this issue and open an other one for the 'hang on crash' behavior.
