### ISSUE TITLE
Ephemeris instructions out of date

### ISSUE THREAD

**Issue by AntoniaR** [transientskp/tkp#542]
The ephemeris on Struis is out of date as dates after 2015/01/01 no longer work and this is blocking the processing of recent RSM data because the ephemeris is used for quality control checks on LOFAR CASA images. I already reported this issue here https://github.com/transientskp/systems/issues/7 but it has not been resolved yet.

We currently use DE405 and the TraP documentation only provides instructions to update from DE400 to DE405 - see: http://tkp.readthedocs.io/en/latest/getstart/casacore-measures-data.html
If you try the test described here with today's date you can see that it fails. So these instructions need updating to whatever fix is appropriate.

This page does give a link to an NRAO help page to update it further: https://casaguides.nrao.edu/index.php/Updating_the_CASA_Data_Repository
but I suspect that I need higher level permissions and we will need to follow the instructions for version 4.4 or earlier (as we're using 4.2).

Alternatively, would simply having an updated CASA available work (we're using 4.2 but 4.7 is available)? Perhaps this would be a quicker/easier/better fix? I have requested an update to CASA here: https://github.com/transientskp/systems/issues/11

**Comment by AntoniaR** [comment]
ok... so I've been trying to dig into this all day and I think I have made a bit of progress... Mostly a better feeling of virtual machines and learned how to install casacore - but hopefully also a bit of progress to solving this problem.

TraP and the ephemeris test are calling casacore which I think is using the DE405 table from casa.  I think this table is the correct name but, as it says on the casacore GitHub page, we need to update it regularly from ftp://ftp.astron.nl/outgoing/Measures/
I **think** this is the fix, we just need to update the files wherever this info is stored (maybe /soft/casa/latest/data/ephemerides/ as this looks the same file structure as the ftp data, but there could be a casacore version hiding somewhere on struis...)

I tried to installing casacore using a virtual machine on Struis with the most up-to-date measures data downloaded as per the instructions here: https://github.com/casacore/casacore
Unfortunately this failed on the very last step as casacore tried to copy a file into /usr/local/bin/casacore_assay which obviously I don't have permission for. Perhaps there was a setting for cmake to prevent this but I didn't manage to find that. For reference my cmake command was
`cmake -DUSE_FFTW3=ON -DDATA_DIR=/home/antoniar/CASA/Measures/iers -DUSE_OPENMP=ON  -DUSE_HDF5=ON -DBUILD_PYTHON=ON -DUSE_THREADS=ON -DPYTHON2_LIBRARY=/home/antoniar/casatest/lib/python2.7/ ..`
I did manage to get it mostly installed but couldn't figure out how to call the correct measures module (it kept defaulting to the struis build of casacore).
So sadly, I was unable to see if this would fix the problem.

I'm currently attempting to build everything on my laptop to test it there, but as my poor old laptop has suffered much over the years I'm not convinced this is going to work... If I can get around my poor laptop issues and manage to test it, I will post another update.

**Comment by AntoniaR** [comment]
Ah wait, to call in python I seem to need `pip install python-casacore`... Just trying that and wondering where python-casacore gets its measures data from.

**Comment by AntoniaR** [comment]
ok, so I got python-casacore to install in my virtual machine and I am calling the right module, but it is still failing. However, I can't figure out if it is using my updated ephemeris in my install of casacore or an old one lying around on Struis. I have posted an issue here to ask for help identifying which data python-casacore is using: https://github.com/casacore/python-casacore/issues/70

Regarding my laptop, where I only have the updated ephemeris data installed, python-casacore has obviously not installed properly as it is leading to a nasty python failure when I try to use `from casacore.measures import measures`, although `import casacore` works fine! So I am getting to a point where I am fully stuck solving this. Any insights/help would be appreciated.

**Comment by gijzelaerr** [comment]
I recommend you just stick with the packaged versions of casacore. Casacore 2.0.3 is installed in struis system wide, I'm not sure which casacore you are using. the system wide casacore is using the casacore-data package, which is automatically updated using the measures data from the astron FTP server. I see now the data has not been updated by astron for the last couple of weeks, not sure if such a short period of no updates can cause the problems. I'll ask 

If you want to install casacore on your own virtual machine or system i recommend you use the packages from the kernsuite: http://kernsuite.info

**Comment by AntoniaR** [comment]
I was trying to confirm that I was calling the most up-to-date ephemeris information, which is the first thing ASTRON would want me to confirm. As I did not know there was a way to force it to take these data from a specific folder (see the instructions here: https://github.com/casacore/python-casacore/issues/70 ). So, I was trying to set-up a clean build where I knew it was only accessing the most recent version in a virtual machine to test this properly.

No, a couple of weeks should not make a difference and it's not working for dates from January 2015 so it's been an issue for a couple of years now. Having done a few confirmation tests that this is a problem with the Measures table, I am now in contact with ASTRON to get this resolved.
