### ISSUE TITLE
regression problem, tkp 4.0 might be slower than tkp 3

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/tkp#544]
@mkuiack please post links to the profiles and logs here.

**Comment by mkuiack** [comment]
The TraP 4.0 project directory ais001:/home/kuiack/mkuiack/speedtest contains profiles and logs. The banana site for the database http://banana.transientskp.org/r4/vlo_speedtest/ is also related bu now gives an "error 500 O no! permission denied for relation dataset" Not sure why or if it'll be accessible. 

If you want to just try start over we can do that. There are lots of images with various subband integrations in ais001:/mnt/nex*/data/images

**Comment by gijzelaerr** [comment]
did you give banana access to the database?

**Comment by mkuiack** [comment]
I'm not sure why I didn't before, but I did now, and it works.

**Comment by gijzelaerr** [comment]
conclusion is, we just try to do much in one go with all the varmetric updating. Impossible to parallelise since everything is done in the database. I think this is a dead end, the next TraP should move away from the design of moving all calculations to the database and just use it for storing lightcurves.
