### ISSUE TITLE
make list of problems/plans/suggestions for Folkert and Gijs replacement

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/tkp#545]
I will make a list of current issues, short term plans and potential long term plans for transient detection using TraP.

**Comment by AntoniaR** [comment]
To avoid duplication, many of the scientific short and long term plans are already listed here: https://github.com/transientskp/tkp/wiki/The-TraP-Banana-Wish-List

**Comment by gijzelaerr** [comment]
ok, good point. I will focus only on TraP from a technical perspective.

**Comment by gijzelaerr** [comment]
here is the initial writeup

https://github.com/transientskp/tkp/blob/master/TODO.md

**Comment by gijzelaerr** [comment]
done
