### ISSUE TITLE
beamwidths_limit job parameter not being used

### ISSUE THREAD

**Issue by ajstewart** [transientskp/tkp#562]
I discovered that the `beamwidths_limit` parameter in `job_params.cfg` is not actually being read in and used by the pipeline (I found this by having an image with a slight offset which I couldn't get to associate some sources no matter what value I put in, deruiter radius was reasonable).

Was this known and intended or an accident?

```
[association]
deruiter_radius = 5.68
beamwidths_limit =  1.0
```

https://github.com/transientskp/tkp/blob/dc3fd8aff123a0def4e6b160714608bcbc4f2a31/tkp/main.py#L252-L259

**Comment by gijzelaerr** [comment]
i guess this is solved now.
