### ISSUE TITLE
Store the local rms for each extraction

### ISSUE THREAD

**Issue by ajstewart** [transientskp/tkp#565]
Currently the local rms is not stored with the extracted sources (seems to be indirectly tied up in the `det_sigma` value. A raw local rms would be a very useful addition.

**Comment by mkuiack** [comment]
I believe `f_int/det_sigma` is the raw local RMS.

**Comment by ajstewart** [comment]
> I believe `f_int/det_sigma` is the raw local RMS.

I wondered that, but the docs say it's `f_peak` (which it should be):

> The significance of the detection (that is, the ratio of the peak flux value to the RMS map at that point).
>
> https://tkp.readthedocs.io/en/latest/userref/structure/stages/extraction.html

Also in the code:
https://github.com/transientskp/tkp/blob/7bb937551d4ca8cd06096fa1740fe7c6df22c256/tkp/sourcefinder/extract.py#L207-L209

**Comment by mkuiack** [comment]
Ah, right, there is also a reference in:

https://tkp.readthedocs.io/en/latest/devref/database/schema.html?highlight=det_sigma

> det_sigma
>
>The significance level of the detection: \(20 \times f_\mathrm{peak} / \mathrm{det_sigma}\) provides the detection RMS.

The factor of 20 isn't explained though. 

I was only able to get constantly reasonable results by using the integrated flux.  This is especially true if you are looking for the local RMS when monitoring positions. When a source is significantly detected there is a very small difference.

**Comment by ajstewart** [comment]
Ok that's good to know (wanting to do it for a monitoring list is one reason that made me look at it).

I've been scratching my head of that factor of 20 for a long time!

**Comment by AntoniaR** [comment]
From Mark's recent work, it seems that we can now reasonably use the database values to recreate the RMS values so I do not think it is necessary to additionally store this value unless you both think we gain more from this.
Suggested improvement for TraP 5.0: correct documentation to reference f_int

**Comment by AntoniaR** [comment]
@ajstewart I assume that as we can reliably recreate the RMS values with numbers in the database that we no longer need to store this value. I am closing this issue for now and please reopen if needed.
