### ISSUE TITLE
Remove capability to store images

### ISSUE THREAD

**Issue by AntoniaR** [transientskp/tkp#573]
The option to store images in MongoDB is no longer used routinely due to rapidly filling up database machines. This was originally implemented for testing and debugging purposes, but has become redundant as the original images are still stored elsewhere and can be accessed directly or through e.g. Jupyter notebooks

I proposed to remove this capability from TraP from Release 5.0. Any objections?

**Comment by ajstewart** [comment]
I agree, it should be removed.
