### ISSUE TITLE
Multiproc functionality not working

### ISSUE THREAD

**Issue by AntoniaR** [transientskp/tkp#602]
I have tried a standard TraP run with typical settings. When running in serial, the pipeline works fine. However, when using the parallel processing option (`method = multiproc ` in pipeline.cfg), I get the following error:
```
15:22:09 ERROR tkp.main: timestep raised <class 'AssertionError'> exception: daemonic processes are not allowed to have children
```
Using branch converted_to_python3_with_sourcefinder_from_pyse_repo.

**Comment by HannoSpreeuw** [comment]
Thanks. My `pipeline.cfg` in `tkp/config/project_template` has `method = "multiproc"`, but this error did not show up when running the unit tests. Is there a simple way to reproduce this error?

**Comment by AntoniaR** [comment]
This error has also been solved since the upgrade of Struis.
