### ISSUE TITLE
Multiproc error: "Daemonic processes are not allowed to have children"

### ISSUE THREAD

**Issue by AntoniaR** [transientskp/tkp#608]
I have been trying out the multiproc and serial versions of TraP. https://github.com/transientskp/tkp/blob/f176bbc567918f3ca32f0b694d98ed557849c802/tkp/config/project_template/pipeline.cfg#L28-L30

With serial, the data is processed correctly. With multiproc, I get the following error:
```13:38:14 ERROR tkp.main: timestep raised <class 'AssertionError'> exception: daemonic processes are not allowed to have children```

**Comment by AntoniaR** [comment]
@HannoSpreeuw The best way to reproduce this error is to run TraP as normal (i.e. not the tests) on a small number of images with the parallel processing option on. I will send you some images for this shortly by email.

**Comment by HannoSpreeuw** [comment]
Thanks, I can reproduce it now.
